GET http://localhost:8080/amenity
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwNywiZW1haWwiOiJoYW1pZHNoYWtlcnk1NkBnbWFpbC5jb20iLCJyb2xlIjoiaG9zdCIsIm5hbWUiOiJoYW1pZCIsImlhdCI6MTc4NDYyMjA5MSwiZXhwIjoxNzg0NzA4NDkxLCJhdWQiOiJsb2NhbGhvc3Q6NTAwMCIsImlzcyI6ImxvY2FsaG9zdDo1MDAwIn0.H6pP2M155X58q9-_e9_hJMkUi1Bm6DkGTTAxjOaRx0o
