export enum Permission {
  HOTEL_CREATE = 'HOTEL_CREATE',
  HOTEL_UPDATE = 'HOTEL_UPDATE',
  HOTEL_DELETE = 'HOTEL_DELETE',

  ROOM_CREATE = 'ROOM_CREATE',
  ROOM_UPDATE = 'ROOM_UPDATE',
  ROOM_DELETE = 'ROOM_DELETE',

  BOOKING_MANAGE = 'BOOKING_MANAGE',
  HOTEL_READ = 'HOTEL_READ',
  BOOKING_READ = 'BOOKING_READ',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOOKING_CANCEL = 'BOOKING_CANCEL',
}
