PATCH http://localhost:8080/reservations/e728c98e-3328-4f63-9ef0-2c3495d59144/confirm-payment
accept-encoding: gzip, deflate, br
accept: */*
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYwLCJlbWFpbCI6InN5c3RlbUBob3RlbGJvb2tpbmcuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODE3ODg0ODAsImV4cCI6MTc4MTg3NDg4MCwiYXVkIjoibG9jYWxob3N0OjUwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NTAwMCJ9.spSLDxA3YvDJdVt35b7KZZUHOEItY0l6eQ8IUhzxyrk


