POST http://localhost:8080/reservations
accept-encoding: gzip, deflate, br
accept: */*
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYwLCJlbWFpbCI6InN5c3RlbUBob3RlbGJvb2tpbmcuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODE3ODg0ODAsImV4cCI6MTc4MTg3NDg4MCwiYXVkIjoibG9jYWxob3N0OjUwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NTAwMCJ9.spSLDxA3YvDJdVt35b7KZZUHOEItY0l6eQ8IUhzxyrk
user-agent: httpyac
{
  "roomId": "cccda5b9-c60a-4299-911f-560fcc6eb0a4",
  "guestName": "Ali",
  "guestPhone": "09123456789",
  "checkInDate": "2026-09-19T00:00:00.000Z",
  "checkOutDate": "2026-09-22T00:00:00.000Z",
  "numberOfGuests": 2,
  "specialRequests": "Non-smoking room"
}
