POST http://localhost:3000/reservations
accept-encoding: gzip, deflate, br
accept: */*
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJlbWFpbCI6ImhhbWloZGdhZmdnc2RmQGdtYWlsLmNvbSIsInJvbGUiOiJob3N0IiwiaWF0IjoxNzc3NTMzNDQ5LCJleHAiOjE3Nzc1MzcwNDksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.AptDJhsgLLTR1a79BjxFmNDKcRFJWzOc0pDGw9MVrQA
user-agent: httpyac
{
  "roomId": "3d62ae37-9ddd-4c98-84b2-947d7d07652c",
  "guestName": "Ali",
  "guestPhone": "09123456789",
  "checkInDate": "2026-09-19T00:00:00.000Z",
  "checkOutDate": "2026-09-22T00:00:00.000Z",
  "numberOfGuests": 2,
  "specialRequests": "Non-smoking room"
}
