POST http://localhost:4000/auth/refresh-token
Content-Type:application/json
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNrbEVZSFJVSERERmtsamtoa0BnbWFpbC5jb20iLCJpYXQiOjE3NzU5MDIzMjIsImV4cCI6MTc3NTkwNTkyMiwiYXVkIjoibG9jYWxob3N0OjQwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NDAwMCJ9.K53XkufmcaRdxFjZCasbcsoCBnhqzUaQ4JVGzuQOmqE
{
"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJpYXQiOjE3NzU5MDIzMjIsImV4cCI6MTc3NTk4ODcyMiwiYXVkIjoibG9jYWxob3N0OjQwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6NDAwMCJ9.n7RMaYnhykOLMgy32scpJM2Y2yMNXLh-2AsDAE1VE-M"
}
