### Create room
POST http://localhost:3000/rooms/hotel/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJlbWFpbCI6ImhhbWloZGdhZmdnc2RmQGdtYWlsLmNvbSIsInJvbGUiOiJob3N0IiwiaWF0IjoxNzc3NDU4NDgxLCJleHAiOjE3Nzc0NjIwODEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.PU2pGBr5MqYpPPzDbZCYrS9FpfmsI3bOmCtOnRdJcgo
{
  "roomNumber":"47",
  "type": "SINGLE",
  "basePrice": 120,
  "capacity": 2,
  "floor": 1,
  "amenities": ["wifi", "tv", "air_conditioner"]
}

