DELETE /hotels/16 HTTP/1.1
Host: localhost:3000
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJlbWFpbCI6ImhhbWloZGdhZmdnc2RmQGdtYWlsLmNvbSIsInJvbGUiOiJob3N0IiwiaWF0IjoxNzc2OTQ4NjczLCJleHAiOjE3NzY5NTIyNzMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.wbwojfhaQuVtfTUfJf-puoR8ndXVg2sfIentyK2K2u4
Content-Type: application/json
