GET http://localhost:3000/hotels/16
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJlbWFpbCI6ImhhbWloZGdhZmdnc2RmQGdtYWlsLmNvbSIsInJvbGUiOiJob3N0IiwiaWF0IjoxNzc2OTQ0MzU1LCJleHAiOjE3NzY5NDc5NTUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.MmTUyVkEr7CLDSuQGmbDA98fdrtftOtaSSyLS9i47oQ


