GET http://localhost:3000/hotels/16
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJlbWFpbCI6ImhhbWloZGdhZmdnc2RmQGdtYWlsLmNvbSIsInJvbGUiOiJob3N0IiwiaWF0IjoxNzc3NzI3MjQ4LCJleHAiOjE3Nzc3MzA4NDgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.6aDkkjpVaS6iIHu1Y6ygt9jmSEGbDgrQehkUyoQho5o


